[package]
name = "p-stake-interface"
version = "0.1.0"
edition = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }

[dependencies]
wincode = { git = "https://github.com/anza-xyz/wincode.git", rev = "6feb75ff4c5b26275b0ee8bc4a12ea906d996a02", default-features = false, features = ["derive"] }

[dev-dependencies]
bincode = "1.3.3"
proptest = "1.9.0"
solana-pubkey = "3.0.0"
solana-stake-interface = { path = "../../interface", features = ["bincode"] }
test-case = "3.3.1"
