[package]
name = "p-stake-interface"
version = "0.1.0"
edition = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }

[dependencies]
# TODO: Waiting on 0.3.0 to be released
wincode = { git = "https://github.com/anza-xyz/wincode.git", rev = "fa70c7c7c13885085f743e4f01deb1a4de0b64fb", default-features = false, features = ["derive"] }

[dev-dependencies]
bincode = "1.3.3"
proptest = "1.9.0"
solana-pubkey = "3.0.0"
solana-stake-interface = { path = "../../interface", features = ["bincode"] }
test-case = "3.3.1"
